### ISSUE TITLE
Ageing pipeline 

### ISSUE THREAD

**Issue by Hamedhm** [mpi2/impc_stats_pipeline#17]
This epic shows the progress in the development of the statistical pipeline for the LA data.

The steps below are required to successfully build the pipeline:

- [ ]  Data collection/integration/documentation
- [ ] Selecting a set of parameters for the research and demonstration
- [ ] Practicing the best visualisations 
- [ ] Discussing internally and with the WGs
- [x] Publishing the paper
-    * [x] Proof of concept
-    * [x] Hit change analysis
-    * [x] Sexual dimorphism
-    * [x] WT-KO analysis
-    * [ ] Association with disease
-    * [ ] Predictions
-    * [ ] Share and feedback from consortium
-    * [ ] final draft of a paper
-    * [ ] submission and follow up

**Comment by marinak-ebi** [comment]
No longer relevant
